---
driver: 
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: false

platforms:
- name: ubuntu-14.04
  driver:
    box: ubuntu-14.04
    box_url: http://mirrors.ooyala.com/vagrant/ubuntu1404.box

suites:
- name: default
  run_list:
    - recipe[powerdns::server]
  attributes: {}
