name             "powerdns"
maintainer       "Bao Nguyen"
maintainer_email "team-ops@ooyala.com"
license          "Apache 2.0"
description      "Installs/Configures PowerDNS"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.4.1"
depends "mariadb"
depends "ooyala-mariadb"
depends "sqlite"

depends "build-essential"
depends "mysql"
depends "git"
depends "resolvconf"
